version: '3.8'

services:
  mongo_db:
    image: mongo:5.0
    container_name: images_mdb
    ports:
      - "27017:27017"
    volumes:
      - ./auth/:/docker-entrypoint-initdb.d/*.js
      - ./mongodb:/data/db 777
    environment:
      MONGO_INITDB_DATABASE: image_db
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
    command: [--auth]